package com.privatebank.business.common.exception;

public enum ErrorCode {
    INVALID_ARGUMENT,
    UNAUTHENTICATED,
    ACCESS_DENIED,
    CUSTOMER_OUT_OF_SCOPE,
    GRAPH_NODE_OUT_OF_SCOPE,
    GRAPH_ROOT_NOT_FOUND,
    GRAPH_NODE_NOT_FOUND,
    GRAPH_SERVICE_UNAVAILABLE,
    GRAPH_QUERY_LIMIT_EXCEEDED,
    RESOURCE_NOT_FOUND,
    STATE_CONFLICT,
    STALE_ARTIFACT,
    DUPLICATE_REVIEW,
    PRECONDITION_FAILED,
    COMPLIANCE_BLOCKED,
    RATE_LIMITED,
    UPSTREAM_ERROR,
    SERVICE_UNAVAILABLE,
    INTERNAL_ERROR
}
