package com.privatebank.common.exception;

public enum ErrorCode {
    INVALID_ARGUMENT,
    UNAUTHENTICATED,
    ACCESS_DENIED,
    CUSTOMER_OUT_OF_SCOPE,
    RESOURCE_NOT_FOUND,
    STATE_CONFLICT,
    STALE_ARTIFACT,
    DUPLICATE_REVIEW,
    PRECONDITION_FAILED,
    COMPLIANCE_BLOCKED,
    RATE_LIMITED,
    UPSTREAM_ERROR,
    SERVICE_UNAVAILABLE,
    INTERNAL_ERROR
}
